### ISSUE TITLE
Error: Calling register endpoint failed, CONNECTION Timeout

### ISSUE THREAD

**Issue by 071bctajay** [IBM/car-auction-network-fabric-node-sdk#2] opened 2019-01-16 04:32 UTC
While registering the user, I am getting the following error:
```
node registerUser.js
 Store path:/home/car-auction-network-fabric-node-sdk/hfc-key-store
Successfully loaded admin from persistence
Failed to register: Error: Calling register endpoint failed, CONNECTION Timeout
```
If I again perform the register action I get this error:
```
node registerUser.js
 Store path:/home/car-auction-network-fabric-node-sdk/hfc-key-store
Successfully loaded admin from persistence
Failed to register: Error: fabric-ca request register failed with errors [[{"code":0,"message":"Registration of 'user1' failed: Identity 'user1' is already registered"}]]
```

**Comment by 071bctajay** [comment] 2019-01-16 04:35
But while invoking I am not able to get the user1 instance:
```
node invoke.js
Store path:/home/dryice/Desktop/Dryice/car-auction-network-fabric-node-sdk/hfc-key-store
Failed to invoke successfully :: Error: Failed to get user1.... run registerUser.js
```

**Comment by 071bctajay** [comment] 2019-01-16 04:35
But while invoking I am not able to get the user1 instance:
```
node invoke.js
Store path:/home/car-auction-network-fabric-node-sdk/hfc-key-store
Failed to invoke successfully :: Error: Failed to get user1.... run registerUser.js
```

**Comment by horeaporutiu** [comment] 2019-01-17 18:30
@071bctajay Thanks for bringing up this issue. Working through this now, and will update you when the issue is fixed.

**Comment by horeaporutiu** [comment] 2019-01-17 20:26
@071bctajay I have replicated the issue.

**Comment by horeaporutiu** [comment] 2019-01-18 03:05
Should be fixed now.

**Comment by pranilchhetri** [comment] 2019-01-18 06:20
I have recently performed the similar action by cloning the latest repo.I have got the same issue:
node registerUser.js
 Store path:/home/pranil/go/src/github.com/hyperledger/car-auction-network-fabric-node-sdk/hfc-key-store
Successfully loaded admin from persistence
Failed to register: Error: Calling register endpoint failed, CONNECTION Timeout

Similar result on next command: node registerUser.js
 node registerUser.js
 Store path:/home/pranil/go/src/github.com/hyperledger/car-auction-network-fabric-node-sdk/hfc-key-store
Successfully loaded admin from persistence
Failed to register: Error: fabric-ca request register failed with errors [[{"code":0,"message":"Registration of 'user' failed: Identity 'user' is already registered"}]]

**Comment by horeaporutiu** [comment] 2019-01-18 18:23
@pranilchhetri @071bctajay Can you try resetting your network, and then trying again? When I did that, mine worked fine.

**Comment by horeaporutiu** [comment] 2019-01-18 18:24
You can do that by clicking on the top right of the IBM Blockchain Platform, right next to your name, and then there should be an option to reset network on the drop-down.

**Comment by ruchika05** [comment] 2019-01-21 07:00
A workaround is to provide the enrollment secret in the fabric_ca_client.register() call, so even though the fabric_ca_client.register() times out, fabric_ca_client.enroll() can be called and the certs will be downloaded.

**Closed as completed** 2019-02-28 21:09 UTC
